CREATE TABLE IF NOT EXISTS SalesUniverse.DIM_ACCOUNT (
	ACCOUNT VARCHAR(3) not NULL,
	`ACCOUNT NAME` VARCHAR(255),
	`CUSTOMER FLAG` VARCHAR(50),
	`EMPLOYEE` VARCHAR(255),
	`SECTOR INDUSTRY` VARCHAR(255),
	`OPEN OPPORTUNITY` VARCHAR(255)
);

LOAD DATA INFILE '/home/ralfano/Documents/test_mysql/demo/demo_data/Account.csv'
INTO TABLE SalesUniverse.DIM_ACCOUNT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


CREATE TABLE IF NOT EXISTS SalesUniverse.DIM_PROVINCE (
	COUNTRY VARCHAR(255) not NULL,
	NAME VARCHAR(255),
	PROVINCE VARCHAR(255),
	PRIMARY KEY ( PROVINCE )
);

LOAD DATA INFILE '/home/ralfano/Documents/test_mysql/demo/demo_data/Province.csv'
INTO TABLE SalesUniverse.DIM_PROVINCE
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


CREATE TABLE IF NOT EXISTS SalesUniverse.DIM_PRODUCT (
	PRODUCT VARCHAR(9) not NULL,
	`PRODUCT NAME` VARCHAR(255),
	CATEGORY VARCHAR(255),
	SUBCATEGORY VARCHAR(255),
	PRIMARY KEY ( PRODUCT )
);

LOAD DATA INFILE '/home/ralfano/Documents/test_mysql/demo/demo_data/Product.csv'
INTO TABLE SalesUniverse.DIM_PRODUCT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


CREATE TABLE IF NOT EXISTS SalesUniverse.DIM_SCENARIO (
	SCENARIO VARCHAR(10) not NULL,
	SCENARIO_NAME VARCHAR(255),
	PRIMARY KEY ( SCENARIO )
);

LOAD DATA INFILE '/home/ralfano/Documents/test_mysql/demo/demo_data/Scenario.csv'
INTO TABLE SalesUniverse.DIM_SCENARIO
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS SalesUniverse.DIM_PERIOD (
	PERIOD VARCHAR (6) not NULL,
	YEAR VARCHAR (4),
	MONTH VARCHAR (2),
	PRIMARY KEY ( PERIOD )
);

LOAD DATA INFILE '/home/ralfano/Documents/test_mysql/demo/demo_data/Period.csv'
INTO TABLE SalesUniverse.DIM_PERIOD
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


CREATE TABLE IF NOT EXISTS SalesUniverse.MEASURE_SET_SALES
(
	Account VARCHAR(3) not NULL,
	Province VARCHAR(255),
	Product VARCHAR(9) not NULL,
	SCENARIO VARCHAR(7) not NULL,
	PERIOD VARCHAR (6) not NULL,
	VALUE_Quantity DOUBLE,
	VALUE_Sales DOUBLE,
	VALUE_Cost DOUBLE
);

LOAD DATA INFILE '/home/ralfano/Documents/test_mysql/demo/demo_data/Sales.csv'
INTO TABLE SalesUniverse.MEASURE_SET_SALES
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

